development:
  host_url: <%= ENV['HOST_URL'] || 'http://localhost:3000' %>
  stripe_publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>
  stripe_secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>

production:
  host_url: <%= ENV['HOST_URL'] %>
  stripe_publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>
  stripe_secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>
